##
## The Bitbucket Application
##
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: 'bitbucket-{{ .Values.bitbucket.cluster }}-{{ .Values.bitbucket.name }}-bitbucket'
#  labels:
#    env: '{{ .Values.env }}'
#    role: '{{ .Values.bitbucket.role }}'
#    type: 'bitbucket'
#spec:
#  project: bbaas-{{ .Values.env }}
#  source:
#    repoURL: 'https://github.com/DraouiBilal/bbaas-deployment.git'
#    path: app/bitbucket
#    targetRevision: '{{ .Values.bitbucket.revision }}'
#    helm:
#      valueFiles:
#        - ../values-common.yaml # Used to get global information
#        - values.yaml
#        - values-common.yaml
#        - values-{{ .Values.env }}.yaml
#      values: |
#        env: '{{ .Values.env }}'
#        bitbucket:
#          cluster: '{{ .Values.bitbucket.cluster }}'
#          name: '{{ .Values.bitbucket.name }}'
#          role: '{{ .Values.bitbucket.role }}'
#          revision: '{{ .Values.bitbucket.revision }}'
#        managedControllers:
#        # Loop on all the Controller instances to manage in Bitbucket
#        # {{- range .Values.elements }}
#        # {{ if .bitbucketEnabled }}
#        - cluster: {{ .cluster }}
#          name: {{ .name }}
#          #{{ if .controllerManageGroups }}
#          controllerManageGroups:
#          #{{- range .controllerManageGroups }}
#          - id: {{ .id }}
#          #{{- end }}
#          #{{ end }}
#        # {{ if .zone }}
#          zone: {{ .zone }}
#        # {{ end }}
#        # {{ end }}
#        # {{- end }}
#      ignoreMissingValueFiles: true
#  destination:
#    name: '{{ .Values.bitbucket.cluster }}'
#    namespace: bitbucket-{{ .Values.bitbucket.name }}-{{ .Values.env }}
#  ignoreDifferences:
#  # Ignore path field from Route generated by Cloudbess chart
#  # because it is empty and creating an ArgoCD useless diff
#  - group: route.openshift.io
#    kind: Route
#    jsonPointers:
#    - /spec/path
#  syncPolicy:
#    syncOptions:
#      - ApplyOutOfSyncOnly=true
#      - PruneLast=true
#    retry:
#      limit: 2
#      backoff:
#        duration: 5s
#        factor: 2
#        maxDuration: 3m
#---
