global:
  bitbucket:
    nodes:
      replicaCount: 1
      jvm:
        minMemory: "1g"
        maxMemory: "3g"
        extraArgs: "-Xss512k"
      config:
        properties: |
          # Server settings
          server.port=7990
          server.baseurl=http://localhost:8080
          server.scheme=http
          server.secure=false
          # Database configuration
          jdbc.driver=org.postgresql.Driver
          jdbc.url=jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/bitbucketdb
          jdbc.user=postgres
          # Shared home directory
          bitbucket.home=/var/atlassian/application-data/bitbucket
          # Clustering (optional, for Data Center)
          hazelcast.network.kubernetes=true
          throttle.resource.scm-hosting=4

        nginx: |
          server {
            listen 8080;
        
            server_name localhost;
        
            location / {
                proxy_pass http://localhost:7990;
                proxy_http_version 1.1;
        
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
            }
          }


    mesh:
      replicaCount: 3
      config:
        nginx: |
          server {
            server_name localhost;
            listen 8081;
            location / {
                proxy_pass http://localhost:7777/;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
            }
          }
  mounts:
    storageClass: standard
    pvcs:
    - name: bitbucket-shared
      storage: 10Gi
      storageClassName: nfs-client
      mountPath: /var/atlassian/application-data/bitbucket/shared
