apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bbaas-mesh
spec:
  replicas: {{ .Values.global.bitbucket.mesh.replicaCount | default 3 }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bbaas-mesh
  template:
    metadata:
      labels:
        app: bbaas-mesh
        app.kubernetes.io/component: bbaas-mesh
        app.kubernetes.io/name: bbaas-mesh
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceName: "bbaas-mesh-https-headless"
      containers:
      - name: bitbucket
        image: atlassian/bitbucket-mesh:2.5.11
        ports:
        - containerPort: 7777
          name: grpc
        volumeMounts:
        - name: bbaas-mesh-config-volume
          mountPath: /var/atlassian/application-data/mesh/
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8081
          name: http
        volumeMounts:
        - name: nginx-mesh-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-mesh-config-volume
        configMap:
          name: nginx-mesh-config-map
          items:
            - key: nginx.conf
              path: nginx.conf

  volumeClaimTemplates:
    - metadata:
        name: bbaas-mesh-config-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
