# Loop on all the PersistentVolumeClaim to claim
{{- range .Values.global.mounts.pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .name }}"
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
  annotations:
    {{- if .storageClassName }}
    volume.beta.kubernetes.io/storage-class: "{{ .storageClassName }}"
    {{- else }}
    volume.beta.kubernetes.io/storage-class: "{{ $.Values.global.storageClass | default "standard" }}"
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .storage }}"
{{- end }}
